## a. Độ dài vector

In [4]:
import numpy as np

# ver 1
def compute_vector_length_v1(vector):
    norm = np.sqrt(np.sum([v ** 2 for v in vector]))
    return norm

# ver 2
def compute_vector_length_v2(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

In [5]:
compute_vector_length_v1(np.array([3, 4]))

np.float64(5.0)

In [6]:
compute_vector_length_v2(np.array([3, 4]))

np.float64(5.0)

## b. Phép tích vô hướng

In [11]:
import numpy as np

def compute_dot_product_v1(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result

def compute_dot_product_v2(vector1, vector2):
    result = np.sum([v1 * v2 for v1, v2 in zip(vector1, vector2)])
    return result

In [12]:
compute_dot_product_v1(np.array([3, 4]), np.array([4, 5]))

np.int64(32)

In [9]:
compute_dot_product_v2(np.array([3, 4]), np.array([4, 5]))

np.int64(32)

## c. Nhân vector với ma trận

In [21]:
import numpy as np

def matrix_multi_vector_v1(matrix, vector):
    result = np.array([np.sum([v1 * v2 for v1, v2 in zip(v, vector)]) for v in matrix])
    return result

def matrix_multi_vector_v2(matrix, vector):
    result = np.dot(matrix, vector)
    return result

In [22]:
matrix_multi_vector_v1(np.array([[1, 2], [3, 4]]), np.array([5, 6]))

array([17, 39])

In [23]:
matrix_multi_vector_v2(np.array([[1, 2], [3, 4]]), np.array([5, 6]))

array([17, 39])

## d. Nhân ma trận với ma trận

In [24]:
import numpy as np

def matrix_multi_matrix(matrix1, matrix2):
    
    result = np.dot(matrix1, matrix2)
    
    return result

In [25]:
matrix_multi_matrix(np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]]))

array([[19, 22],
       [43, 50]])

## e. Ma trận nghịch đảo

Cho trước $A = \begin{bmatrix}
-2 & 6 \\
8 & -4 
\end{bmatrix}$ Tìm $A^{-1}$.




Giải:

${det(A)$ = $-2 * -4 - 8 * 6 = -40$<br>

$A^{-1} = \frac{1}{-40} \begin{bmatrix}
-4 & -6 \\
-8 & -2
\end{bmatrix} = \begin{bmatrix}
0.1 & 0.15 \\
0.2 & 0.05
\end{bmatrix}$


In [26]:
import numpy as np

def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    
    return result

In [27]:
inverse_matrix(np.array([[1, 2], [3, 4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])