In [1]:
final_answer = []

def answer(choice):
    final_answer.append(choice)

## Câu 1

In [2]:
import numpy as np

def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

In [3]:
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))

23.28


In [4]:
answer('d')

## Câu 2

In [5]:
import numpy as np

def compute_dot_product(vector1, vector2):
    result = np.dot(vector1, vector2)
    return result

In [6]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])

result = compute_dot_product(v1, v2)
print(round(result, 2))

4


In [7]:
answer('b')

## Câu 3

In [8]:
x = np.array([[1, 2], 
              [3, 4]])

k = np.array([1, 2])
print('result \n', x.dot(k))

result 
 [ 5 11]


In [9]:
answer('a')

## Câu 4

In [10]:
x = np.array([[-1, 2], 
              [3, -4]])

k = np.array([1, 2])
print('result \n', x @ k)

result 
 [ 3 -5]


In [11]:
answer('b')

## Câu 5

In [12]:
def matrix_multi_vector(matrix, vector):
    result = np.dot(matrix, vector)
    return result

In [13]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])

result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [14]:
answer('a')

## Câu 6

In [15]:
def matrix_multi_matrix(matrix1, matrix2):
    
    result = np.dot(matrix1, matrix2)
    
    return result

In [16]:
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])

result = matrix_multi_matrix(m1, m2)    
print(result)

[[  6  -1]
 [-16 -10]]


In [17]:
answer('c')

## Câu 7

In [18]:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

result = m1 @ m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [19]:
answer('a')

## Câu 8

In [20]:
m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4))[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])

result = m1 @ m2
print(result)

[5. 5. 5. 5.]


In [21]:
answer('d')

## Câu 9

In [22]:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1, 4), 'F')[0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])

result = m1 @ m2
print(result)

[29 29 29 29]


In [23]:
answer('b')

## Câu 10

In [24]:
import numpy as np

def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    
    return result

In [25]:
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [26]:
answer('a')

## Câu 11

In [27]:
import numpy as np

def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    
    return eigenvalues, eigenvectors

In [28]:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [29]:
answer('a')

## Câu 12

In [30]:
import numpy as np

def compute_cosine(v1, v2):
    cos_sim = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    
    return cos_sim

In [31]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])

result = compute_cosine(x, y)
print(round(result, 3))

0.577


In [32]:
answer('c')

In [33]:
for idx, ans in enumerate(final_answer):
    print(f'Câu {idx + 1}: {ans}')

Câu 1: d
Câu 2: b
Câu 3: a
Câu 4: b
Câu 5: a
Câu 6: c
Câu 7: a
Câu 8: d
Câu 9: b
Câu 10: a
Câu 11: a
Câu 12: c
